name: job-chain

on:
  workflow_dispatch:
    branches: [ main ]

jobs:

  pre-job:
    runs-on: ubuntu-latest
    steps:
    - name: set-variables
      id: set-variables
      run: |
        EXAMPLE_TIMESTAMP=$(echo "$(date +%Y%m%d%H%M%S)")
        echo "::set-output name=timestamp::$EXAMPLE_TIMESTAMP"
    outputs:
      timestamp: ${{ steps.set-variables.outputs.timestamp }}

  main-job:
    needs: pre-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - [aaa, bbb, ccc]
          - [ddd, eee, fff]
          - [ggg, hhh, iii]
    steps:
      - run: |
          for p in ${{ matrix.project }}
          do
            echo "parallel step $p with variable ${{ needs.pre-job.outputs.timestamp }}"
          done

  post-job:
    needs: [pre-job, main-job]
    runs-on: ubuntu-latest
    steps:
    - name: show variable
      run: echo "${{ needs.pre-job.outputs.timestamp }}"

