name: shell-scripting

on:
  workflow_dispatch:
    branches: [ main ]

jobs:

  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - id: conditional
        shell: bash
        run: |
          set -ex
          CONDITION=`'true'`
          if $CONDITION; then
            echo "condition is: $CONDITION"
          fi

